# Generated by Django 3.1.5 on 2021-01-26 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(default='email', max_length=100)),
                ('adress', models.CharField(max_length=255)),
                ('phone_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False)),
                ('date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=11)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pet_Shop.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock', models.IntegerField()),
                ('category_id_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='pet_Shop.category')),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_number', models.IntegerField()),
                ('date', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pet_Shop.orders')),
            ],
        ),
        migrations.AddField(
            model_name='orders',
            name='product',
            field=models.ManyToManyField(related_name='order', to='pet_Shop.Product'),
        ),
    ]
