# Generated by Django 3.1.3 on 2021-01-31 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_Shop', '0018_mymodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mymodel',
            old_name='userid',
            new_name='username',
        ),
    ]
