# Generated by Django 3.1.3 on 2021-01-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_Shop', '0019_auto_20210131_1121'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='customer',
        ),
        migrations.AddField(
            model_name='orders',
            name='username',
            field=models.CharField(blank=True, default=None, max_length=45),
        ),
    ]
