# Generated by Django 3.1.3 on 2021-01-31 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_Shop', '0021_auto_20210131_1138'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Employee',
        ),
    ]
